### ISSUE TITLE
API improvements related to asInstanceOf

### ISSUE THREAD

**Issue by scordio** [joel-costigliola/assertj-core#1605]
## Summary
Some existing APIs can benefit from a chained `asInstanceOf` invocation in order to obtain more specialized assertions, for example the methods which change the current object under test.

For these cases, it would be convenient to have an overloaded method which expects an `InstanceOfAssertFactory` as additional parameter.

**Happy to receive any feedback!**

### Syntax sugar for InstanceOfAssertFactory parameter
- [x] To improve readability for the cases mentioned above, a static method `as` can be provided in ~`InstanceOfAssertFactories`~ `Assertions` (#1609).
```java
public static <T, ASSERT extends AbstractAssert<?, ?>> InstanceOfAssertFactory<T, ASSERT> as(InstanceOfAssertFactory<T, ASSERT> assertFactory) {
  return assertFactory;
}
```
The approach is similar to [`Assertions#from`](https://github.com/joel-costigliola/assertj-core/blob/7deb7821cc84991bc23375ca2b8054cea5a9200c/src/main/java/org/assertj/core/api/Assertions.java#L1961-L1977).

### AbstractObjectAssert
- [X] `extracting(String, InstanceOfAssertFactory)` (#1581):
```java
TolkienCharacter frodo = new TolkienCharacter("Frodo", 33, HOBBIT);
// Current
assertThat(value).extracting("name")
                 .asInstanceOf(STRING)
                 .startsWith("Fro");
// Improvement
assertThat(value).extracting("name", as(STRING))
                 .startsWith("Fro");
```
- [X] `extracting(Function, InstanceOfAssertFactory)` (#1588):
```java
TolkienCharacter frodo = new TolkienCharacter("Frodo", 33, HOBBIT);
// Current
assertThat(value).extracting(TolkienCharacter::getName)
                 .asInstanceOf(STRING)
                 .startsWith("Fro");
// Improvement
assertThat(value).extracting(TolkienCharacter::getName, as(STRING))
                 .startsWith("Fro");
```

### AbstractMapAssert
- [x] `extractingByKey(Object, InstanceOfAssertFactory)` (#1623, #1619):
```java
Map<String, Object> map = new HashMap<>();
map.put("name", "kawhi");
// Current
assertThat(map).extractingByKey("name")
                 .asInstanceOf(STRING)
                 .startsWith("kaw");
// Improvement
assertThat(value).extractingByKey("name", as(STRING))
                 .startsWith("kaw");
```

### AbstractIterableAssert
- [x] `element(int, InstanceOfAssertFactory)` (#1649):
```java
Iterable<String> hobbits = newArrayList("Frodo", "Sam", "Pippin");
// Current
assertThat(hobbits).element(1)
                   .asInstanceOf(STRING)
                   .startsWith("Sa");
// Improvement
assertThat(hobbits).element(1, as(STRING))
                   .startsWith("Sa");
```
- [x] `first(InstanceOfAssertFactory)` (#1644):
```java
Iterable<String> hobbits = newArrayList("Frodo", "Sam", "Pippin");
// Current
assertThat(hobbits).first()
                   .asInstanceOf(STRING)
                   .startsWith("Fro");
// Improvement
assertThat(hobbits).first(as(STRING))
                   .startsWith("Fro");
```
- [x] `last(InstanceOfAssertFactory)` (#1647):
```java
Iterable<String> hobbits = newArrayList("Frodo", "Sam", "Pippin");
// Current
assertThat(hobbits).last()
                   .asInstanceOf(STRING)
                   .startsWith("Pip");
// Improvement
assertThat(hobbits).last(as(STRING))
                   .startsWith("Pip");
```

### AbstractOptionalAssert
- [x] `get(InstanceOfAssertFactory)` (#1635):
```java
Optional<String> hobbit = Optional.of("Frodo");
// Current
assertThat(hobbit).get()
                  .asInstanceOf(STRING)
                  .startsWith("Fro");
// Improvement
assertThat(hobbit).get(as(STRING))
                  .startsWith("Fro");
```

**Comment by joel-costigliola** [comment]
I'm all for it :)
A few things to do :

- add soft assertions tests related to this, I think it should work without additional work but it's always tricky when mixing soft assertions and changing the object under test.
- it would be great to start adding doc and release notes in https://github.com/assertj/doc for that feature in a next release branch.

**Comment by joel-costigliola** [comment]
@scordio  looks like this can be close but I'll let you do it in case you had more work to do in mind.
